name: CML Workflow

on:
  push:
    branches:
      - main  # Run the workflow when there is a push to the main branch

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run machine learning script
        run: |
          python train.py
          echo "Model Metrics"
          cat metrics.txt

